site_name: Mission Data Management Solution
repo_url: https://github.com/eanderson-ei/gtm-dms-alpha
edit_uri: edit/main/docs/
site_description: Atlas is an open-source solution for managing the full data lifecycle for Missions. 
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js
theme:
  name: material
  custom_dir: docs/overrides
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes # (allows pages associated with section groups)
    - search.share
    - search.suggest
    - search.highlight
  font:
    text: Source Sans Pro
extra:
  generator: false
markdown_extensions:
  - admonition
  - md_in_html
  - pymdownx.details
  - pymdownx.snippets
  - footnotes
  - attr_list

# Page tree
nav:
  - 'Home': 'index.md' 
  - 'Get Started':
    - 'pages/get-started/index.md'
    - 'Installation': pages/get-started/installation.md
    - 'Setup': 
      - pages/get-started/setup/index.md
      - '1. Set Up Data Steward Admin Tool': 'pages/get-started/setup/setup-admin.md'
      - '2. Set Up Atlas Directory': 'pages/get-started/setup/setup-drive.md'
      - '3. Set Up Mission Database': 'pages/get-started/setup/setup-missiondb.md'
      - '4. Set Up Web Applications': 'pages/get-started/setup/setup-webapps.md'
  - 'Usage':
    - 'pages/usage/index.md'
    - 'Update Mission Database': 'pages/usage/regular.md'
  - 'Design':
    - 'Architecture': 
      - 'pages/design/Architecture/README.md'
      - 'Activity Data': 'pages/design/Architecture/Activity Data/README.md'
      - 'Activity Location Data': 'pages/design/Architecture/Activity Location Data/README.md'
      - 'Performance Measures': 'pages/design/Architecture/Performance Measures/README.md'
      - 'Thematic Data': 'pages/design/Architecture/Thematic Data/README.md'
    - 'Pipelines': 
      - 'pages/design/Pipelines/README.md'
      - 'Activity Data': 'pages/design/Pipelines/Activity Data/README.md'
      - 'Activity Location Data': 'pages/design/Pipelines/Activity Location Data/README.md'
      - 'Thematic Data': 'pages/design/Pipelines/Thematic Data/README.md'
    - 'Components': 
      - 'pages/components/index.md'
      - 'Mission Database': 'pages/components/mission-database.md'
      - 'Activity Folder': 'pages/components/activity-folder.md'
      - 'Data Steward Admin Tool': 'pages/components/data-steward-admin.md'
      - 'Activity Database': 'pages/components/activity-database.md'
      - 'Activity Location Data Tracker': 'pages/components/activity-location-tracker.md'
      - 'Activity Location Data Compiler': 'pages/components/activity-location-compiler.md'
      - 'Thematic Database': 'pages/components/thematic-database.md'
      - 'Data Catalog': 'pages/components/data-catalog.md'
      - 'Map Viewer': 'pages/components/map-viewer.md'
      - 'Activity Location Data Portal (Public)': 'pages/components/ald-portal-public.md'
  - 'Knowledge':
    - 'Knowledge Base':
      - 'pages/knowledge/base/index.md'
      - 'Database Options': 'pages/knowledge/base/database-rationale.md'
      - 'Pipeline Options': 'pages/knowledge/base/data-pipeline-rationale.md'
      - 'PostgreSQL': 'pages/knowledge/base/postgres.md'
      - 'pgAdmin': 'pages/knowledge/base/pgAdmin.md'
      - 'PSQL': 'pages/knowledge/base/psql.md'
      - 'Add PSQL to PATH': 'pages/knowledge/base/add-psql-to-path.md'
      - 'SQL': 'pages/knowledge/base/SQL.md'
      - 'Latin Characters': 'pages/knowledge/base/latin-characters.md'
      - 'H3': 'pages/knowledge/base/h3.md'
      - 'IMPORTRANGE': 'pages/knowledge/base/importrange.md'
      - 'Staging Data': 'pages/knowledge/base/staging-data.md'
    - 'Playbook':
      - 'pages/knowledge/playbook/index.md'
      - 'Stakeholder Engagement': 'pages/knowledge/playbook/stakeholder-engagement.md'
